"""Compress the dashboard at build time and emit it as a byte array.

The readable src/index_html.h stays the source; src/index_html_gz.h is derived
from it automatically. So there is still only one file to edit, and the ESP32
serves gzip regardless: about a third of the bytes, so the page is up
correspondingly sooner.
"""
import gzip, os, re

SRC = os.path.join("src", "index_html.h")
DST = os.path.join("src", "index_html_gz.h")


def build():
    raw = open(SRC, encoding="utf-8").read()
    m = re.search(r'R"HTML\((.*?)\)HTML"', raw, re.S)
    if not m:
        raise SystemExit("gzip_html: raw string not found in %s" % SRC)
    html = m.group(1).encode("utf-8")
    packed = gzip.compress(html, 9)

    out = ["// Generated by tools/gzip_html.py - do not edit by hand.",
           "// Source: src/index_html.h",
           "#pragma once",
           "#include <Arduino.h>",
           "",
           "static const size_t INDEX_HTML_GZ_LEN = %d;" % len(packed),
           "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {"]
    for i in range(0, len(packed), 16):
        out.append("    " + ",".join("0x%02x" % b for b in packed[i:i + 16]) + ",")
    out.append("};")
    text = "\n".join(out) + "\n"

    if not os.path.exists(DST) or open(DST, encoding="utf-8").read() != text:
        open(DST, "w", encoding="utf-8").write(text)
    print("gzip_html: %d -> %d bytes (%.0f %%)" %
          (len(html), len(packed), 100.0 * len(packed) / len(html)))


build()
